<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_ChequeBookLeaves</name>
   <tag></tag>
   <elementGuidId>0a8cf274-dc0d-41c2-b5e0-51ebd1e5614c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[text()='25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1615382107517</value>
   </webElementProperties>
</WebElementEntity>
