<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_ChequeLeaf</name>
   <tag></tag>
   <elementGuidId>0c2e2121-a535-4fd0-859e-72a9eeecc05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id-770e2a5d-395e-4324-b253-2591e0cd2646-39-vrp_attribute_chequebookleaves8-vrp_attribute_chequebookleaves.fieldControl-option-set-select']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
